# skylantern demo site, written by scripts/export-prepackaged.py
defaultLanguage=en
defaultSite=false
description=Demonstration website of Skylantern Airways, a fictional airline, built with the classic-templates template set for Jahia.
installedModules.1=classic-templates
installedModules.2=classic-travel
installedModules.3=default
installedModules.4=siteSettings
installedModules.5=site-settings-seo
language.en.activated=true
language.en.mandatory=false
language.fr.activated=true
language.fr.mandatory=false
language.zh.activated=false
language.zh.mandatory=false
mixLanguage=false
sitekey=skylantern
siteservername=localhost
siteservernamealiases=
sitetitle=Skylantern Airways
templatePackageName=classic-templates
