# classic-dev demo site, written by scripts/export-prepackaged.py
defaultLanguage=en
defaultSite=false
description=A demonstration site for the classic-templates template set.
installedModules.1=classic-templates
installedModules.2=default
installedModules.3=siteSettings
installedModules.4=site-settings-seo
language.en.activated=true
language.en.mandatory=false
language.fr.activated=true
language.fr.mandatory=false
mixLanguage=false
sitekey=classic-dev
siteservername=localhost
siteservernamealiases=
sitetitle=Classic Dev
templatePackageName=classic-templates
